export const STORE_ITEMS = Object.freeze([
  {
    id: 'pro_monthly',
    source: 'stripe',
    kind: 'plan',
    billingMode: 'subscription',
    billingInterval: 'month',
    billingIntervalCount: 1,
    name: 'Pro',
    description: 'Full skill reports, unlimited assessed practice, interview tracks, and advanced duel analytics.',
    stripeAmountCents: 1900,
    currency: 'usd',
    durationDays: 30,
    planName: 'Pro',
    planScope: 'individual',
    popular: true,
    bestValue: false,
  },
  {
    id: 'interview_sprint',
    source: 'stripe',
    kind: 'plan',
    billingMode: 'fixed_term',
    name: 'Interview Sprint',
    description: 'An 8-week interview-readiness package with focused benchmark, practice, and challenge coverage.',
    stripeAmountCents: 14900,
    currency: 'usd',
    durationDays: 56,
    planName: 'Interview Sprint',
    planScope: 'individual',
    popular: false,
    bestValue: false,
  },
  {
    id: 'coins_150',
    source: 'stripe',
    kind: 'coin_pack',
    name: '150 Coins',
    description: 'Starter stack',
    coinsGranted: 150,
    stripeAmountCents: 199,
    currency: 'usd',
    bonusPercent: 0,
    popular: false,
    bestValue: false,
  },
  {
    id: 'coins_420',
    source: 'stripe',
    kind: 'coin_pack',
    name: '420 Coins',
    description: 'First real upgrade',
    coinsGranted: 420,
    stripeAmountCents: 499,
    currency: 'usd',
    bonusPercent: 12,
    popular: false,
    bestValue: false,
  },
  {
    id: 'coins_900',
    source: 'stripe',
    kind: 'coin_pack',
    name: '900 Coins',
    description: 'Most players start here',
    coinsGranted: 900,
    stripeAmountCents: 999,
    currency: 'usd',
    bonusPercent: 20,
    popular: true,
    bestValue: false,
  },
  {
    id: 'coins_1900',
    source: 'stripe',
    kind: 'coin_pack',
    name: '1,900 Coins',
    description: 'Best balance of value and flexibility',
    coinsGranted: 1900,
    stripeAmountCents: 1999,
    currency: 'usd',
    bonusPercent: 26,
    popular: false,
    bestValue: false,
  },
  {
    id: 'coins_3000',
    source: 'stripe',
    kind: 'coin_pack',
    name: '3,000 Coins',
    description: 'Built for long streaks and resets',
    coinsGranted: 3000,
    stripeAmountCents: 2999,
    currency: 'usd',
    bonusPercent: 33,
    popular: false,
    bestValue: true,
  },
  {
    id: 'coins_5600',
    source: 'stripe',
    kind: 'coin_pack',
    name: '5,600 Coins',
    description: 'Competitive grind bundle',
    coinsGranted: 5600,
    stripeAmountCents: 4999,
    currency: 'usd',
    bonusPercent: 49,
    popular: false,
    bestValue: false,
  },
  {
    id: 'coins_12000',
    source: 'stripe',
    kind: 'coin_pack',
    name: '12,000 Coins',
    description: 'Maximum bonus, longest runway',
    coinsGranted: 12000,
    stripeAmountCents: 9999,
    currency: 'usd',
    bonusPercent: 59,
    popular: false,
    bestValue: false,
  },
  {
    id: 'xp_boost_2x_1h',
    source: 'coins',
    kind: 'xp_boost',
    name: '2x XP Boost',
    description: '1 hour duration',
    coinCost: 120,
    durationHours: 1,
    multiplier: 2,
    popular: false,
    bestValue: false,
  },
  {
    id: 'xp_boost_2x_3h',
    source: 'coins',
    kind: 'xp_boost',
    name: '2x XP Boost',
    description: '3 hours duration',
    coinCost: 300,
    durationHours: 3,
    multiplier: 2,
    popular: true,
    bestValue: false,
  },
  {
    id: 'xp_boost_3x_1h',
    source: 'coins',
    kind: 'xp_boost',
    name: '3x XP Boost',
    description: '1 hour duration',
    coinCost: 180,
    durationHours: 1,
    multiplier: 3,
    popular: false,
    bestValue: false,
  },
  {
    id: 'heart_refill',
    source: 'coins',
    kind: 'heart_refill',
    name: 'Refill Hearts',
    description: 'Restore all hearts',
    coinCost: 60,
    popular: false,
    bestValue: false,
  },
  {
    id: 'unlimited_hearts_1h',
    source: 'coins',
    kind: 'unlimited_hearts',
    name: 'Unlimited Hearts',
    description: '1 hour duration',
    coinCost: 220,
    durationHours: 1,
    popular: false,
    bestValue: false,
  },
  {
    id: 'unlimited_hearts_3h',
    source: 'coins',
    kind: 'unlimited_hearts',
    name: 'Unlimited Hearts',
    description: '3 hours duration',
    coinCost: 500,
    durationHours: 3,
    popular: true,
    bestValue: false,
  },
  {
    id: 'unlimited_hearts_24h',
    source: 'coins',
    kind: 'unlimited_hearts',
    name: 'Unlimited Hearts',
    description: '24 hours duration',
    coinCost: 1500,
    durationHours: 24,
    popular: false,
    bestValue: true,
  },
]);

export const STORE_ITEMS_BY_ID = new Map(STORE_ITEMS.map((item) => [item.id, Object.freeze({ ...item })]));

export const STRIPE_STORE_ITEMS = Object.freeze(STORE_ITEMS.filter((item) => item.source === 'stripe'));
export const COIN_STORE_ITEMS = Object.freeze(STORE_ITEMS.filter((item) => item.source === 'coins'));
export const PLAN_STORE_ITEMS = Object.freeze(STORE_ITEMS.filter((item) => item.kind === 'plan'));

export function getStoreItem(itemId) {
  return STORE_ITEMS_BY_ID.get(itemId) || null;
}

export function isStripeStoreItem(item) {
  return Boolean(item && item.source === 'stripe');
}

export function isCoinStoreItem(item) {
  return Boolean(item && item.source === 'coins');
}

export function isPlanStoreItem(item) {
  return Boolean(item && item.kind === 'plan');
}

export function isSubscriptionPlanStoreItem(item) {
  return Boolean(item && item.kind === 'plan' && item.billingMode === 'subscription');
}
